### ISSUE TITLE
Missing Toolchain

### ISSUE THREAD

**Issue by toolboc** [ppcasm/HYCU#2]
Where can the toolchain required by HYCU_HS be obtained?  The [Makefile](https://github.com/ppcasm/HYCU/blob/master/HYCU_HS/Makefile#L8) alludes to a toolchain by name of 'C:\Sunplus\S_CORE~1.1\gnu\bin'.   

I assume that SunPlus has long retired this software.  Are there any other options available to build the console side loader?

**Comment by ppcasm** [comment]
Ill see if i can dig it up over the next few days, but you could cross compile it with an old version of gcc, but inhave the s+core ide  for windows somewhere Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Paul DeCarlo <notifications@github.com> Date: 1/21/20  6:20 PM  (GMT-05:00) To: ppcasm/HYCU <HYCU@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [ppcasm/HYCU] Missing Toolchain (#2) Where can the toolchain required by HYCU_HS be obtained?  The Makefile alludes to a toolchain by name of 'C:\Sunplus\S_CORE~1.1\gnu\bin'.
I assume that SunPlus has long retired this software.  Are there any other options available to build the console side loader?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ppcasm/HYCU/issues/2?email_source=notifications\u0026email_token=AAFMZMUQ2TUZMWIQ65E2DGTQ657KJA5CNFSM4KJ435VKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IHZH6KA",
"url": "https://github.com/ppcasm/HYCU/issues/2?email_source=notifications\u0026email_token=AAFMZMUQ2TUZMWIQ65E2DGTQ657KJA5CNFSM4KJ435VKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IHZH6KA",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ppcasm** [comment]
https://www.dropbox.com/s/mbe71pbhsa83tg8/S%2Bcore%20IDE-V2.6.1.exe?dl=1
Try this

**Comment by toolboc** [comment]
@ppcasm, 

The attached IDE seems to build the .bin file appropriately, however, after renaming to HYPER.EXE and burning to a data disc, I see a "Loading" screen but it never proceeds.  I've tried two different brands of CD-R, both high quality Taiyo Yuden based.  Any ideas?

**Comment by ppcasm** [comment]
Maybe burn on lowest speed. There is a potentiometer on the drive laser
that you can adjust, but as far as I can tell i was the only one that ever
did it and i never documented it other than trial and error, but the reason
for doing the mod was so that i could use cd-rw since i got tired of
ruining cds while testing. Precisely the reason for the loader as it
allowed me to do quick tests without burning anything. It was cumbersome.
Also, just for shits, try holding the hyperscan upside down while its
loading. Its likely the brand of cdr but i dont remember what brand worked
for me

**Comment by ppcasm** [comment]
By brand i dont particularly mean vheap vs expensive. When you hold it up
to the light is it lightly, or extremely transparent?

**Comment by toolboc** [comment]
@ppcasm,

I didn't have any luck attempting to boot with the device upside down, it will usually ask me to "Insert Disc" but when I attempt right-side up it always gets stuck on "Loading". 

Currently using [Taiyo Youden based CD-Rs](https://www.amazon.com/gp/product/B01HFBO78W/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1s) and imation CD-Rs that are very lightly transparent, burning at lowest speed, and also tried moving HYPER.EXE to end of disc with dummy data to no avail.

The S+core IDE did mention on start that migration steps should be taken for projects created in an earlier version of the IDE.  The suggestions in the accompanying notes seem to be accounted for in the generated files.

I'll try to see if I can find some other brands of CD-Rs around the house and report back.

**Comment by toolboc** [comment]
@ppcasm,

I Tried with 2 different Memorex CD-Rs and TDK brand CD-R and experiencing same behavior.  

To rule out the CD-Rs being at fault, I ripped an .iso of X-men and burned it back to a Taiyo Youden based CD-R and it booted just fine.  This has me certain that something is something wrong with the build output of the S+Core IDE.

To clarify, the disc should proceed beyond the loading screen without presence of an MCU. The code and your uploaded video seem to indicate this to be the expected behavior.  i.e. the disc should just boot and draw a prompt with nothing more than a properly burned CD-R?

Any chance you might be able to validate building and burning a bootable CD-R from current source using the attached IDE?

**Comment by ppcasm** [comment]
There is a possibility that maybe the linker isnt setup correctly, though all of that should've carried over. Ill look at it when i get a chance
null

**Comment by toolboc** [comment]
@ppcasm,

That seems a very likely culprit, for the record, producing a build from the IDE forces the following change to the linker script:

![image](https://user-images.githubusercontent.com/2018336/73574328-16881e00-443b-11ea-9784-196a414caa9b.png)

**Comment by toolboc** [comment]
@ppcasm,

That was the issue, the IDE regenerates the resources and linker script with default settings.  PR incoming with fixed .bcs to ensure proper generation.
